services:
  - type: web
    name: whatsapp-bot-cispn
    env: node
    region: oregon
    plan: starter
    buildCommand: bash render-build.sh
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/project/.cache/puppeteer
    disk:
      name: whatsapp-session-data
      mountPath: /opt/render/project/src/tokens
      sizeGB: 1
